name: ci

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build xorg-dev libxi-dev libxrandr-dev libxinerama-dev libxcursor-dev libx11-dev libxext-dev libasound2-dev libgtk-3-dev clang-tidy
      - name: Configure
        run: cmake --preset linux
      - name: clang-tidy
        run: run-clang-tidy -p build/linux

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install clang-format
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format
      - name: Check formatting
        run: |
          clang-format --version
          clang-format --dry-run --Werror $(git ls-files '*.cpp' '*.hpp' '*.c' '*.h')

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build xorg-dev libxi-dev libxrandr-dev libxinerama-dev libxcursor-dev libx11-dev libxext-dev libasound2-dev libgtk-3-dev
      - name: Configure
        run: cmake --preset linux -DLIZARD_EMBED_ASSETS=ON
      - name: Build (type check)
        run: cmake --build build/linux --config Release --target LizardHook

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build xorg-dev libxi-dev libxrandr-dev libxinerama-dev libxcursor-dev libx11-dev libxext-dev libasound2-dev libgtk-3-dev
      - name: Configure
        run: cmake --preset linux -DLIZARD_EMBED_ASSETS=ON
      - name: Build
        run: cmake --build build/linux --config Release
      - name: Test
        run: ctest --test-dir build/linux --output-on-failure

  build:
    name: ${{ matrix.os }}-${{ matrix.arch }}
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: ubuntu-latest
            os: linux
            arch: x64
            preset: linux
            artifact: LizardHook-linux-x64.tar.gz
            ext: tar.gz
            configure_args: ""
          - runner: ubuntu-latest
            os: linux
            arch: arm64
            preset: linux
            artifact: LizardHook-linux-arm64.tar.gz
            ext: tar.gz
            configure_args: "-DCMAKE_SYSTEM_PROCESSOR=aarch64"
          - runner: macos-latest
            os: macos
            arch: x64
            preset: macos
            artifact: LizardHook-macos-x64.zip
            ext: zip
            configure_args: "-DCMAKE_OSX_ARCHITECTURES=x86_64"
          - runner: macos-latest
            os: macos
            arch: arm64
            preset: macos
            artifact: LizardHook-macos-arm64.zip
            ext: zip
            configure_args: "-DCMAKE_OSX_ARCHITECTURES=arm64"
          - runner: windows-latest
            os: windows
            arch: x64
            preset: win-mingw
            artifact: LizardHook-win-x64.zip
            ext: zip
            configure_args: ""
    steps:
      - uses: actions/checkout@v4

      - name: Setup prerequisites (Linux)
        if: matrix.runner == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build xorg-dev libxi-dev libxrandr-dev libxinerama-dev libxcursor-dev libx11-dev libxext-dev libasound2-dev libgtk-3-dev

      - name: Setup prerequisites (macOS)
        if: matrix.runner == 'macos-latest'
        run: brew install ninja || true

      - name: Setup MinGW (Windows)
        if: matrix.runner == 'windows-latest'
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          install: mingw-w64-x86_64-gcc mingw-w64-x86_64-ninja

      - name: Configure
        run: cmake --preset ${{ matrix.preset }} -DLIZARD_EMBED_ASSETS=ON ${{ matrix.configure_args }}
        shell: bash

      - name: Build
        run: cmake --build build/${{ matrix.preset }} --config Release
        shell: bash

      - name: Install
        run: cmake --install build/${{ matrix.preset }} --prefix install/${{ matrix.preset }}-${{ matrix.arch }}
        shell: bash

      - name: Package
        run: |
          cd install/${{ matrix.preset }}-${{ matrix.arch }}
          if [ "${{ matrix.ext }}" = "tar.gz" ]; then
            tar czf ../../${{ matrix.artifact }} *
          else
            zip -r ../../${{ matrix.artifact }} *
          fi
        shell: bash

      - name: Verify linkage
        run: |
          if [ "${{ matrix.runner }}" = "ubuntu-latest" ]; then
            ldd install/${{ matrix.preset }}-${{ matrix.arch }}/LizardHook || true
          elif [ "${{ matrix.runner }}" = "macos-latest" ]; then
            otool -L install/${{ matrix.preset }}-${{ matrix.arch }}/LizardHook || true
          else
            dumpbin /DEPENDENTS install/${{ matrix.preset }}-${{ matrix.arch }}/LizardHook.exe || true
          fi
        shell: bash

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact }}
          path: ${{ matrix.artifact }}

